- name: deploy zabbix-agent config
  copy:
    src: "{{ role_path }}/files/zabbix_agentd.conf"
    dest: /etc/zabbix/zabbix_agentd.conf

- name: restart zabbix agent
  shell: |
    set -e

    sudo mkdir -p /var/log/zabbix /etc/zabbix/zabbix_agentd.d
    sudo touch /var/log/zabbix/zabbix_agentd.log
    sudo chown -R zabbix:zabbix /var/log/zabbix /etc/zabbix/zabbix_agentd.d

    if [[ -f /etc/init.d/zabbix-agent ]];
    then
      /etc/init.d/zabbix-agent restart
    else
      sudo systemctl restart zabbix-agent.service
    fi
  args:
    executable: /bin/bash
