- name: deploy zabbix-agent config
  copy:
    src: "{{ role_path }}/files/zabbix_agentd.conf"
    dest: /etc/zabbix/zabbix_agentd.conf

- name: restart zabbix agent
  shell: |
    set -e
    if [[ -f /etc/init.d/zabbix-agent ]];
    then
      /etc/init.d/zabbix-agent restart
    else
      sudo systemctl restart zabbix-agent.service
    fi
  args:
    executable: /bin/bash
