- name: deploy zabbix-agent config
  template:
    src: "{{ role_path }}/files/zabbix_agentd.conf.j2"
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
  vars:
    zabbix_server: "{{ lookup('env', 'ZABBIX_SERVER') | regex_replace('^https://(.*)$', '\\1') }}"

- name: create zabbix-agent log dir
  file:
    path: /var/log/zabbix
    owner: zabbix
    group: zabbix
    state: directory

- name: create zabbix log file
  copy:
    content: ""
    dest: /var/log/zabbix/zabbix_agentd.log
    force: no
    owner: zabbix
    group: zabbix
    mode: 0755

- name: create zabbix-agent agentd.d dir
  file:
    path: /etc/zabbix/zabbix_agentd.d
    owner: zabbix
    group: zabbix
    state: directory

- name: restart zabbix agent
  shell: |
    set -e
    if [[ -f /etc/init.d/zabbix-agent ]];
    then
      /etc/init.d/zabbix-agent restart
    else
      sudo systemctl enable zabbix-agent.service
      sudo systemctl restart zabbix-agent.service
    fi
  args:
    executable: /bin/bash
