- name: deploy zabbix-agent config
  template:
    src: "{{ role_path }}/files/zabbix_agentd.conf.j2"
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
  vars:
    zabbix_server_domain_name: "{{ zabbix_server | regex_replace('^(https|http)://(.*)$', '\\2') }}"

- name: create zabbix-agent log dir
  file:
    path: /var/log/zabbix
    owner: zabbix
    group: zabbix
    state: directory

- name: create zabbix log file
  copy:
    content: ""
    dest: /var/log/zabbix/zabbix_agentd.log
    force: no
    owner: zabbix
    group: zabbix
    mode: 0755

- name: create zabbix-agent agentd.d dir
  file:
    path: /etc/zabbix/zabbix_agentd.d
    owner: zabbix
    group: zabbix
    state: directory

- name: restart zabbix agent
  shell: |
    set -e
    service=$((pidof systemd &> /dev/null) && echo "systemd" || echo "other")
    if [[ $service == "systemd" ]];
    then
      sudo systemctl enable zabbix-agent.service
      sudo systemctl restart zabbix-agent.service
    else
      /etc/init.d/zabbix-agent restart
    fi
  args:
    executable: /bin/bash
