---
- name: get ubuntu codename
  shell: lsb_release -c | sed -n -r 's/^Codename:\s+(.*)$/\1/p'
  register: ubuntu_codename

- set_fact:
    ubuntu_codename: "{{ ubuntu_codename.stdout }}"

- name: add zabbix repository
  shell: |
    set -e
    ZABBIX_RELEASE_DEB=zabbix-release_4.4-1+{{ ubuntu_codename }}_all.deb
    wget https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/$ZABBIX_RELEASE_DEB
    dpkg -i $ZABBIX_RELEASE_DEB
    apt-get update

- name: install zabbix-agent (apt)
  become: yes
  apt:
    name: zabbix-agent
    state: present
