---
- include_tasks: set-necessary-facts.yml

- import_tasks: set-hostname.yml
  become: yes
  when: current_hostname | regex_search("^ip-\d{1,3}-\d{1,3}-\d{1,3}-\d{1,3}(\.ec2\.internal)?$")

- import_tasks: install-zabbix-agent.yml
  become: yes

- import_tasks: deploy-zabbix-agent.yml
  become: yes
