---
- include_tasks: set-necessary-facts.yml

- name: set instance hostname
  command: "hostname {{ instance_name | replace('_', '') }}-{{ private_ip }}"
  become: yes
  when: current_hostname | regex_search("^ip-\d{1,3}-\d{1,3}-\d{1,3}-\d{1,3}(\.ec2\.internal)?$")

- name: update instance security groups
  command: "python {{ role_path }}/files/add_zabbix_agent_security_group.py {{ instance_id }}"
  delegate_to: localhost

- import_tasks: install-zabbix-agent.yml
  become: yes

- import_tasks: deploy-zabbix-agent.yml
  become: yes
